version: 2
updates:
  # .NET (NuGet)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 2

  # Frontend (npm / SvelteKit)
  - package-ecosystem: "npm"
    directory: "/cryptotracker.web"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 2

  # Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"        # Root Dockerfile
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 2

  # GitHub Actions (Security & Build Workflow)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
