// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cryptotracker.database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250110083815_integration_manual")]
    partial class integration_manual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cryptotracker.database.Models.Asset", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFiat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Symbol");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("cryptotracker.database.Models.AssetMeasuring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StandingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("StandingValue")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("IntegrationId");

                    b.ToTable("AssetMeasurings");
                });

            modelBuilder.Entity("cryptotracker.database.Models.AssetPriceHistory", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.HasKey("Symbol", "Date", "Currency");

                    b.ToTable("AssetPriceHistory");
                });

            modelBuilder.Entity("cryptotracker.database.Models.ExchangeIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsManual")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExchangeIntegrations");
                });

            modelBuilder.Entity("cryptotracker.database.Models.AssetMeasuring", b =>
                {
                    b.HasOne("cryptotracker.database.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cryptotracker.database.Models.ExchangeIntegration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("cryptotracker.database.Models.AssetPriceHistory", b =>
                {
                    b.HasOne("cryptotracker.database.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });
#pragma warning restore 612, 618
        }
    }
}
