maxfilldays: 10
basecurrency: chf
# stockapi: yahoofinance
auth:
  secret: <min 32 characters>
  allowregistration: false
oidc:
  autoprovision: true
integrations:
  - name: Coinbase
    type: coinbase
    key: key
    secret: secret
    description: description
  - name: Bitpanda
    type: bitpanda
    key: key
    secret: secret
    description: description
