maxfilldays: 10
basecurrency: chf
timezone: Europe/Zurich
stockapi: yahoofinance
auth:
  secret: <min 32 characters>
  allowregistration: false
oidc:
  autoprovision: true
integrations:
  - name: Coinbase
    description: description
    sources:
      - type: coinbase
        key: key
        secret: secret
  - name: Ledger
    description: hardware wallet with several chains
    sources:
      - type: bitcoin
        key: zpub...
      - type: ethereum
        key: 0x...
      - type: ripple
        key: r...