<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CryptoClients.Net" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="NBitcoin" />
    <PackageReference Include="YahooFinanceApi" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\cryptotracker.database\cryptotracker.database.csproj" />
  </ItemGroup>

</Project>
